name: Unsplash Endpoints CI/CD

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY  }}

      - name: Build
        run: cargo build --verbose

      - name: Run linter
        run: cargo clippy --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Build Docker Image
        run: docker build -t unsplash-api:latest .

      - name: Configure Docker Client
        run: gcloud auth configure-docker --quiet

      - name: Push Docker Image to Container Registry (GCR)
        run: |-
          docker tag unsplash-api:latest gcr.io/website-353503/unsplash-api:latest
          docker push gcr.io/website-353503/unsplash-api:latest

      - name: Deploy
        uses: "google-github-actions/deploy-cloudrun@v0"
        with:
          image: "gcr.io/website-353503/unsplash-api:latest"
          service: "unsplash-api"
