name: Unsplash Endpoints Pull Request Check

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  PR-Check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@cargo-llvm-cov

      - name: Build
        run: cargo build --verbose

      - name: Run linter
        run: cargo clippy --verbose

      - name: Generate code coverage
        run: cargo llvm-cov
